### ISSUE TITLE
Does not support Interfaces of ScriptableObjects

### ISSUE THREAD

**Issue by ndumais** [Kellojo/Unity-Simple-Loot-Table#2]
Trying to add an interface which is inherited by a Scriptable Objects in a custom Loot Table does not work since it

` must be convertible to 'UnityEngine.Object' in order to use it as parameter`

This would be useful for games which have multiple type of loot which all inherit the same interface

**Comment by ndumais** [comment]
I've done some testing removing all the `where T : Object`, only thing is it would need a different way of getting object names, so possibly implement an interface that has GetName() for Drop.name.

**Comment by ndumais** [comment]
I've refactored everything to use an interface called `INameable` instead of `Object` but there's still and issue with some of the code.

![image](https://user-images.githubusercontent.com/48096495/227967999-903eecc9-b1f4-4a08-a19c-fe0d2b6ff54c.png)

It has to do with all the Serialized Properties I believe.

![image](https://user-images.githubusercontent.com/48096495/227969207-04c7ff92-4b56-458f-80a5-a8047bba9dec.png)

The interfaces are always of ScriptableObjects but I'm not quite sure how to make that clear in the code, if it's possible. I'll probably just use plain ScriptableObjects for now as I have no idea on how to do this. Might be too complex.

**Comment by Kellojo** [comment]
I think this is a super hard problem to solve, as you kind of want both, the flexibility of only being able to pick a certain class and the ease of use the UnityEngine.Object provides.

In my projects I use the same base class for these kinds of situations i.e. an empty class that inherits from ScriptableObject and I can then create a custom loot table for this, which looks for this class specifically. You then have the benefit of only being able to pick the "correct" ScriptableObjects. Maybe this works for you 😄
