### ISSUE TITLE
Weight 1 is Never Rolled

### ISSUE THREAD

**Issue by ndumais** [Kellojo/Unity-Simple-Loot-Table#3]
With the following setup, the item with weight 1 will never be rolled despite saying it should be 33% of the time here, an easy workaround is to use weight 20 and 10 instead of 2 and 1 for example.

![image](https://user-images.githubusercontent.com/48096495/227986309-8c034208-286e-49cc-a794-f19527b1161a.png)

**Comment by Kellojo** [comment]
Hi @ndumais, thank you for reporting the issue 😄 
I adjusted the weights as you mentioned and they now are multiplied by 10 before being taken into account for the drop calculation. This of course doesn't resolve the underlying issue but nicely works around the issue for the time being.
